# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64eee82602c6dcd0132b61d15a771aa4ba9ca4ce027b13c0b7cb4cdaceea149f0bb8e0614127b30712265179f430067a0e4f9d4cc669bb0d45a3797eaed3b00d

test:
  secret_key_base: 87ed1c9decbb7b8e0d75427df0954b192f1e3508c1f422849f483fa5697d48e9149af53cadfa986189ba094b84db04b80b6dfb570747a8fce1a9430e77545143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
